import { connectDB } from "../../../utils/db";
import Events from "../../../models/Events";
import mongoose from "mongoose";

const { ObjectId } = mongoose.Types;

const DEFAULT_TEACHER_ID = new ObjectId("6714cece7ff9cc65162bec06");

// Generate random coordinates within Morocco
function randomMoroccoCoords() {
  const lat = 27 + Math.random() * (35 - 27); // between Laayoune and Tangier
  const long = -13 + Math.random() * 2; // Western Morocco
  return [lat, long];
}

// Generate random date range (in future)
function randomDateRange() {
  const now = new Date();
  const start = new Date(
    now.getTime() + Math.random() * 10 * 24 * 60 * 60 * 1000
  ); // within 10 days
  const end = new Date(start.getTime() + 2 * 24 * 60 * 60 * 1000); // 2 days after
  return `${start.toISOString().slice(0, 16)} to ${end
    .toISOString()
    .slice(0, 16)}`;
}

// Format & validate each event
function prepareEvent(raw) {
  const dateStr = raw.date_of_events || randomDateRange();
  const [startDate, endDate] = dateStr
    .split("to")
    .map((d) => new Date(d.trim()));

  const [lat, long] = raw.location?.coordinates || randomMoroccoCoords();

  return {
    _id: new ObjectId(),
    teacher_id: DEFAULT_TEACHER_ID,
    title: raw.title || "Untitled Event",
    desc: raw.desc || "No description provided.",
    community_service_offered: raw.community_service_offered ?? 5,
    date_of_events: dateStr,
    contact_email: raw.contact_email || "default@event.com",
    category: raw.category || "general",
    max: raw.max || 100,
    link_to_event: raw.link_to_event || "https://example.com",
    createdAt: new Date().toISOString(),
    expiration_date: endDate.toISOString(),
    location: {
      type: "Point",
      coordinates: [long, lat], // GeoJSON format: [long, lat]
    },
    locationName: raw.locationName || "Somewhere in Morocco",
    req: raw.req || "",
    school_id: raw.school_id || "defaultSchoolId",
    sponsored: raw.sponsored ?? false,
    sponsoredLocations: raw.sponsoredLocations || [],
    associationId: raw.associationId || "",
    associationProfilePic: raw.associationProfilePic || "",
    attendance: raw.attendance || {},
    additional: raw.additional || "",
    only_allow_school_volunteers: raw.only_allow_school_volunteers ?? false,
    only_allow_school_see: raw.only_allow_school_see ?? false,
    only_allow_associations_see: raw.only_allow_associations_see ?? false,
    type_of_event: raw.type_of_event || "volunteer",
    tickets: raw.tickets || [],
    eventMode: raw.eventMode || "volunteer",
    attendees: raw.attendees || 0,
    askForPhone: raw.askForPhone ?? false,
    purchasedTickets: raw.purchasedTickets || [],
    eventImage: raw.eventImage || "",
  };
}

const hardcodedEvents = [
  {
    _id: "event_1",
    title:
      "فرصة للشباب من جميع جهات المغرب للمشاركة في برنامج تطويري مميز مع Ken.",
    desc: "تطلق Ken. دعوة لتقديم الترشيحات لبرنامج وطني موجه للشباب المغاربة الذين تتراوح أعمارهم بين 18 و 30 سنة. يهدف هذا البرنامج إلى تعزيز المهارات القيادية، تشجيع المشاركة المجتمعية، تحفيز الابتكار الاجتماعي، وإنشاء شبكة من القادة الشباب.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1744898724/opportunities/covers/z5gwkg07ad6rxapqktsf.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 10,
    date_of_events: "2025-06-10 to 2025-06-15",
    eventMode: "volunteer",
    locationName: "Casablanca, Morocco",
    teacher_id: null,
    associationId: "assoc_1",
    additional: "allowAll",
  },
  {
    _id: "event_2",
    title: "PLURAL+ Youth Video Festival 2025",
    desc: "The PLURAL+ Youth Video Festival invites young people worldwide to submit creative videos on migration, diversity, and social inclusion. Winners join a prestigious awards ceremony and network with global changemakers.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1744752315/opportunities/covers/olwduca1utro9oagsdsu.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [{ price: "20", currency: "USD" }],
    community_service_offered: 0,
    date_of_events: "2025-07-25 to 2025-08-01",
    eventMode: "volunteer",
    locationName: "New York, USA",
    teacher_id: null,
    associationId: "assoc_2",
    additional: "allowAll",
  },
  {
    _id: "event_3",
    title: "4.7 Day ESD Chalk Art Competition 2025",
    desc: "The 4.7 Day ESD Chalk Art Competition encourages learners to use chalk art to promote Education for Sustainable Development, inspiring conversations on global citizenship, climate action, and equity.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1744751963/opportunities/covers/amsoa5l3ztivhdhmsobt.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 15,
    date_of_events: "2025-03-15 to 2025-03-20",
    eventMode: "volunteer",
    locationName: "Paris, France",
    teacher_id: null,
    associationId: "assoc_3",
    additional: "allowAll",
  },
  {
    _id: "event_4",
    title:
      "UNEP Champions of the Earth Award 2025 – UN’s Highest Environmental Honour",
    desc: "The Champions of the Earth Award by UNEP honors individuals and organizations for innovative solutions addressing climate change, pollution, and biodiversity loss, with a focus on methane emissions, sustainable buildings, and clean air.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1744751573/opportunities/covers/bq9onuhmqdwkrl7185ry.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 0,
    date_of_events: "2025-07-05 to 2025-07-10",
    eventMode: "volunteer",
    locationName: "Nairobi, Kenya",
    teacher_id: null,
    associationId: "assoc_4",
    additional: "allowAll",
  },
  {
    _id: "event_5",
    title:
      "Prix Visions Jeunesses 2025 – Récompenser les récits portés sur les jeunesses",
    desc: "Le Prix Visions Jeunesses by Ashoka France rewards inspiring youth-focused media productions, offering 3,000 € and distribution to winners for original written, audio, visual, or graphic works.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1744673610/opportunities/covers/m44psuk06pcfgjnmwq24.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 0,
    date_of_events: "2025-05-25 to 2025-05-30",
    eventMode: "volunteer",
    locationName: "Lyon, France",
    teacher_id: null,
    associationId: "assoc_5",
    additional: "allowAll",
  },

  {
    _id: "event_7",
    title:
      "برنامج ريادة الأعمال للشباب المقاولين – دعم مشاريع في الفلاحة، الفلاحة التحويلية والخدمات الرقمية المرتبطة بها",
    desc: "برنامج ريادة الأعمال يدعم 100 شاب وشابة في تحويل أفكارهم الفلاحية إلى مشاريع ملموسة من خلال التكوين، المواكبة، والاستشارة القانونية، مع التركيز على الاقتصاد الأخضر.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1744412364/opportunities/covers/o0eqzi7iy1oswc0xkz0r.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 5,
    date_of_events: "2025-09-10 to 2025-09-15",
    eventMode: "volunteer",
    locationName: "Marrakech, Morocco",
    teacher_id: null,
    associationId: "assoc_7",
    additional: "allowAll",
  },
  {
    _id: "event_8",
    title: "UN SDG Action Awards 2025 – Heroes of Tomorrow",
    desc: "The UN SDG Action Awards celebrate individuals and initiatives driving sustainable development through creativity and innovation, with winners honored at a global ceremony in Rome.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1744376909/opportunities/covers/sjb1lx0nd5nlcvukvrb7.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 0,
    date_of_events: "2025-10-24 to 2025-10-29",
    eventMode: "volunteer",
    locationName: "Rome, Italy",
    teacher_id: null,
    associationId: "assoc_8",
    additional: "allowAll",
  },
  {
    _id: "event_9",
    title:
      "Training on International Climate Negotiations – 4C Maroc (April 2025)",
    desc: "4C Maroc offers fully funded training for young African and Arab climate leaders to master international climate policy processes under the UNFCCC, focusing on Moroccan and regional priorities.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1744160399/opportunities/covers/g8lctubcyctowvh7ba6l.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 10,
    date_of_events: "2025-04-21 to 2025-04-25",
    eventMode: "volunteer",
    locationName: "Rabat, Morocco",
    teacher_id: null,
    associationId: "assoc_9",
    additional: "allowAll",
  },
  {
    _id: "event_10",
    title: "Funding for climate-related student research in Africa 2025",
    desc: "The Climate Research Fund for African Students supports undergraduate and postgraduate research on climate themes like renewable energy and climate adaptation, offering funding and mentorship.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1744158758/opportunities/covers/ctlqtdwb21iienvbw5vx.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 0,
    date_of_events: "2025-07-20 to 2025-07-25",
    eventMode: "volunteer",
    locationName: "Accra, Ghana",
    teacher_id: null,
    associationId: "assoc_10",
    additional: "allowAll",
  },
  {
    _id: "event_11",
    title:
      "Fully Funded International Conservation Congress in Abu Dhabi – 2025",
    desc: "A global conservation event for youth to showcase sustainable initiatives, network with experts, and build partnerships for biodiversity and climate action, with all costs covered.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1744156823/opportunities/covers/zm9cz46r2vbbqabk6ro3.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 5,
    date_of_events: "2025-05-05 to 2025-05-10",
    eventMode: "volunteer",
    locationName: "Abu Dhabi, UAE",
    teacher_id: null,
    associationId: "assoc_11",
    additional: "allowAll",
  },
  {
    _id: "event_12",
    title: "Green Hydrogen Camp Tunisia",
    desc: "A fully funded summer school and hackathon in Tunisia for EU and MENA students to explore renewable hydrogen technologies through workshops, site visits, and a 48-hour hackathon.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1744133774/opportunities/covers/ka2ic1joxkawyf6wqhnq.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 10,
    date_of_events: "2025-07-07 to 2025-07-11",
    eventMode: "volunteer",
    locationName: "Tunis, Tunisia",
    teacher_id: null,
    associationId: "assoc_12",
    additional: "allowAll",
  },
  {
    _id: "event_13",
    title: "UNESCO Clubs Worldwide Youth Multimedia Competition 2025",
    desc: "UNESCO invites youth to submit sustainable solutions aligned with SDGs via video, essay, or presentation, with winners receiving scholarships and a chance to attend a U.S. summer camp.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743891402/opportunities/covers/ih6horxysvppphirfyds.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 0,
    date_of_events: "2025-08-15 to 2025-08-20",
    eventMode: "volunteer",
    locationName: "Washington D.C., USA",
    teacher_id: null,
    associationId: "assoc_13",
    additional: "allowAll",
  },
  {
    _id: "event_14",
    title:
      "ARLEM Award 2025 – Young Local Entrepreneurship in the Mediterranean",
    desc: "The ARLEM Award honors young Mediterranean entrepreneurs supported by local authorities, announced at the 16th ARLEM Plenary in Palermo, fostering economic collaboration.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743890989/opportunities/covers/pjgdwofwz6u1incrz9xq.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 0,
    date_of_events: "2025-04-25 to 2025-04-30",
    eventMode: "volunteer",
    locationName: "Palermo, Italy",
    teacher_id: null,
    associationId: "assoc_14",
    additional: "allowAll",
  },
  {
    _id: "event_15",
    title: "One World Summit Italy 2025",
    desc: "A global event in Milan gathering young leaders to discuss innovative solutions for global challenges, fostering idea exchange and leadership development.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743817279/opportunities/covers/wyrbpzsygbzki1vyufyt.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 5,
    date_of_events: "2025-07-28 to 2025-07-31",
    eventMode: "volunteer",
    locationName: "Milan, Italy",
    teacher_id: null,
    associationId: "assoc_15",
    additional: "allowAll",
  },
  {
    _id: "event_16",
    title: "MENA Scholarship Programme (MSP) – Morocco 2025",
    desc: "The MSP offers short-term training in the Netherlands for Moroccan professionals aged 20–45, empowering them in priority sectors through top Dutch institutions.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743799576/opportunities/covers/spycmhcsuxujjbizbp5l.png",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 0,
    date_of_events: "2025-03-25 to 2025-03-30",
    eventMode: "volunteer",
    locationName: "Amsterdam, Netherlands",
    teacher_id: null,
    associationId: "assoc_16",
    additional: "allowAll",
  },
  {
    _id: "event_17",
    title: "دعوة لتقديم مقترحات – دعم الصناعات الثقافية والإبداعية في المغرب",
    desc: "دعوة بتمويل 6.9 مليون يورو لدعم الصناعات الثقافية والإبداعية في المغرب، تشمل دعم رواد الأعمال الشباب وبرامج التكوين والمبادرات المشتركة مع أوروبا.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743789811/opportunities/covers/lwz9jmq1asmdnzopiblh.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 2,
    date_of_events: "2025-07-10 to 2025-07-15",
    eventMode: "volunteer",
    locationName: "Rabat, Morocco",
    teacher_id: null,
    associationId: "assoc_17",
    additional: "allowAll",
  },
  {
    _id: "event_18",
    title:
      "Lab Innova Morocco 2025 – Training & Internationalization for Innovative Moroccan Startups",
    desc: "Lab Innova Morocco supports 20 Moroccan startups in circular economy and sustainable development with training, coaching, and a study tour in Italy.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743788981/opportunities/covers/hsq54t2hyzrj8qm0hcz2.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 5,
    date_of_events: "2025-05-15 to 2025-05-20",
    eventMode: "volunteer",
    locationName: "Rabat, Morocco",
    teacher_id: null,
    associationId: "assoc_18",
    additional: "allowAll",
  },
  {
    _id: "event_19",
    title:
      "InspireHER Contest 2025 – Empowering Women Entrepreneurs in the MENA Region",
    desc: "The InspireHER Contest supports MENA women entrepreneurs with awards, capacity-building, and networking, celebrated at the UfM Women Business Forum in Palermo.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743722457/opportunities/covers/p4hwihbvtrzbj7v1vftz.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 7,
    date_of_events: "2025-06-05 to 2025-06-10",
    eventMode: "volunteer",
    locationName: "Palermo, Italy",
    teacher_id: null,
    associationId: "assoc_19",
    additional: "allowAll",
  },
  {
    _id: "event_20",
    title: "Deepfake AI Competition – DeepTech Summit 2025",
    desc: "A national Moroccan competition to develop AI solutions against deepfakes, part of the DeepTech Summit, with winners rewarded in Benguerir.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743721698/opportunities/covers/ew81is3v33y2pooaboyt.png",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 0,
    date_of_events: "2025-04-10 to 2025-04-15",
    eventMode: "volunteer",
    locationName: "Benguerir, Morocco",
    teacher_id: null,
    associationId: "assoc_20",
    additional: "allowAll",
  },
  {
    _id: "event_21",
    title: "COAL Prize 2025 – Freshwater Edition",
    desc: "The COAL Prize invites artists to submit projects on freshwater, offering €12,000 and a residency to winners for transformative ecological proposals.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743720093/opportunities/covers/iigqzlztkshugtxxaxox.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 15,
    date_of_events: "2025-08-01 to 2025-08-05",
    eventMode: "volunteer",
    locationName: "Brussels, Belgium",
    teacher_id: null,
    associationId: "assoc_21",
    additional: "allowAll",
  },
  {
    _id: "event_22",
    title: "Summer Program 2025",
    desc: "A UNESCO Center for Peace summer program offering Model UN, STEAM, or local project tracks to enhance leadership and cultural exchange among global youth.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743634192/opportunities/covers/dev7dqpp98dni0a7shpa.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 10,
    date_of_events: "2025-07-20 to 2025-08-02",
    eventMode: "volunteer",
    locationName: "Virginia, USA",
    teacher_id: null,
    associationId: "assoc_22",
    additional: "allowAll",
  },
  {
    _id: "event_23",
    title: "Volunteering Opportunity in Spain: LearnInRural",
    desc: "LearnInRural engages 48 youth from rural areas in Spain, Turkey, Hungary, and Morocco in volunteering to create educational environments and promote social inclusion.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743553345/opportunities/covers/p0xly5nylgvltffcj1no.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 20,
    date_of_events: "2025-09-01 to 2025-09-07",
    eventMode: "volunteer",
    locationName: "Seville, Spain",
    teacher_id: null,
    associationId: "assoc_23",
    additional: "allowAll",
  },
  {
    _id: "event_24",
    title: "Green Fellowship Program 2025",
    desc: "The Green Fellowship Program supports young sustainability leaders with conferences, community service, and mentorship to become visible changemakers.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743311124/opportunities/covers/o4drzj7g4yjwpfewvth0.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 10,
    date_of_events: "2025-06-25 to 2025-06-30",
    eventMode: "volunteer",
    locationName: "Cape Town, South Africa",
    teacher_id: null,
    associationId: "assoc_24",
    additional: "allowAll",
  },
  {
    _id: "event_25",
    title: "Leading Scholarship – One Young World Summit 2025",
    desc: "Fully funded access to the One Young World Summit for young leaders from underrepresented countries to connect with global changemakers in Munich.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743208576/opportunities/covers/kssijsazv3pqh8ozn6ro.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 5,
    date_of_events: "2025-11-03 to 2025-11-06",
    eventMode: "volunteer",
    locationName: "Munich, Germany",
    teacher_id: null,
    associationId: "assoc_25",
    additional: "allowAll",
  },
  {
    _id: "event_26",
    title: "2025 Jacobs Teen Innovation Challenge",
    desc: "A global virtual competition for teens aged 13–18 to develop SDG-aligned solutions using design thinking, fostering innovation and community impact.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743207778/opportunities/covers/tzbkkn95klsdhh5iy7rb.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 0,
    date_of_events: "2025-04-15 to 2025-04-20",
    eventMode: "volunteer",
    locationName: "Online",
    teacher_id: null,
    associationId: "assoc_26",
    additional: "allowAll",
  },
  {
    _id: "event_27",
    title: "The Possibilists Global Changemaker Survey 2025",
    desc: "A global survey for young changemakers to share insights on social and environmental innovation, offering rewards like workshops and coaching sessions.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1743179050/opportunities/covers/nso9agzrry8rl1z1wiov.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 12,
    date_of_events: "2025-05-10 to 2025-05-15",
    eventMode: "volunteer",
    locationName: "Vienna, Austria",
    teacher_id: null,
    associationId: "assoc_27",
    additional: "allowAll",
  },

  {
    _id: "event_29",
    title: "Entrepreneurship World Cup 2025",
    desc: "A global pitch competition for entrepreneurs from over 200 countries, offering $1 million in prizes, mentorship, and investor connections.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1742954044/opportunities/covers/uphef2ybkpomi8rhdnll.png",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 13,
    date_of_events: "2025-06-15 to 2025-06-20",
    eventMode: "volunteer",
    locationName: "Dubai, UAE",
    teacher_id: null,
    associationId: "assoc_29",
    additional: "allowAll",
  },
  {
    _id: "event_30",
    title: "Action With Africa Challenge 2025",
    desc: "An Enactus Germany initiative supporting entrepreneurial projects tackling Africa’s challenges, offering up to €30,000 in funding for sustainable development.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1742950936/opportunities/covers/csi6h7gvljcqpascyctc.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 15,
    date_of_events: "2025-08-05 to 2025-08-10",
    eventMode: "volunteer",
    locationName: "Berlin, Germany",
    teacher_id: null,
    associationId: "assoc_30",
    additional: "allowAll",
  },
  {
    _id: "event_31",
    title: "Fuzé - Digital Africa 2025 Accelerator Program",
    desc: "Fuzé by Digital Africa supports African tech startups with €20,000–€100,000 funding, mentoring, and industry connections to scale innovative ventures.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1742949837/opportunities/covers/pnupiikw5bucv11ramsp.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 23,
    date_of_events: "2025-05-25 to 2025-05-30",
    eventMode: "volunteer",
    locationName: "Lagos, Nigeria",
    teacher_id: null,
    associationId: "assoc_31",
    additional: "allowAll",
  },
  {
    _id: "event_32",
    title: "MTF Pitch 2025",
    desc: "MTF Pitch offers early-stage tech startups a chance to win £30,000 by pitching at the Muslim Tech Fest in London, with mentorship and investor connections.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1742530195/opportunities/covers/osz9u5bu6m8seq1zujii.png",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 12,
    date_of_events: "2025-07-15 to 2025-07-20",
    eventMode: "volunteer",
    locationName: "London, UK",
    teacher_id: null,
    associationId: "assoc_32",
    additional: "allowAll",
  },

  {
    _id: "event_34",
    title: "Wanted: Social Entrepreneur in Morocco",
    desc: "BOOKBRIDGE seeks social entrepreneurs in Morocco to build profitable social businesses with coaching, team support, and a 0% interest loan.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1741832234/opportunities/covers/mauzo37vpwounagoxnry.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 25,
    date_of_events: "2025-04-20 to 2025-04-25",
    eventMode: "volunteer",
    locationName: "Fez, Morocco",
    teacher_id: null,
    associationId: "assoc_34",
    additional: "allowAll",
  },
  {
    _id: "event_35",
    title: "Green Small-Scale Innovative Projects Competition",
    desc: "A competition supporting green projects in Morocco with $5,000–$60,000 grants for renewable energy, water management, and sustainable agriculture.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1741831627/opportunities/covers/pezpnxopxqryihsgxz1j.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 30,
    date_of_events: "2025-07-27 to 2025-08-01",
    eventMode: "volunteer",
    locationName: "Tangier, Morocco",
    teacher_id: null,
    associationId: "assoc_35",
    additional: "allowAll",
  },
  {
    _id: "event_36",
    title: "CorpsAfrica Volunteer Program – Morocco",
    desc: "A 10-month volunteer program for young Moroccans to serve rural communities, co-creating sustainable projects with training and support.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1741745466/opportunities/covers/yef70j8mfg4djypru7ny.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 25,
    date_of_events: "2025-05-05 to 2025-05-10",
    eventMode: "volunteer",
    locationName: "Oujda, Morocco",
    teacher_id: null,
    associationId: "assoc_36",
    additional: "allowAll",
  },
  {
    _id: "event_37",
    title:
      "Moroccan Youth Council for Diplomatic and International Cooperation",
    desc: "An initiative engaging young Moroccans globally to support Morocco’s diplomatic efforts, promoting unity and international relations.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1741731310/opportunities/covers/vxlmmdheingmqv5w2ds5.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 10,
    date_of_events: "2025-07-20 to 2025-07-25",
    eventMode: "volunteer",
    locationName: "Rabat, Morocco",
    teacher_id: null,
    associationId: "assoc_37",
    additional: "allowAll",
  },
  {
    _id: "event_38",
    title: "Digital Energy Challenge 2025",
    desc: "A challenge to develop digital solutions for energy access and renewable energy integration in Africa, co-funded by the EU, AFD, and ADEME.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1741729553/opportunities/covers/mfwv4tgrxxj4eq5yfy1z.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 15,
    date_of_events: "2025-06-25 to 2025-06-30",
    eventMode: "volunteer",
    locationName: "Addis Ababa, Ethiopia",
    teacher_id: null,
    associationId: "assoc_38",
    additional: "allowAll",
  },
  {
    _id: "event_39",
    title:
      "UNICEF Venture Fund: Equity-Free Funding Opportunity for Fem Tech Solutions",
    desc: "The UNICEF Venture Fund offers up to $100K in equity-free funding for startups using AI, data science, or blockchain to improve women’s and girls’ healthcare and economic participation.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1741556213/opportunities/covers/xmpbjimqmhohmjgacein.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 15,
    date_of_events: "2025-05-15 to 2025-05-20",
    eventMode: "volunteer",
    locationName: "Geneva, Switzerland",
    teacher_id: null,
    associationId: "assoc_39",
    additional: "allowAll",
  },
  {
    _id: "event_40",
    title: "[Fully Funded] COP30 preparation and mobilization program",
    desc: "A program empowering Global South youth to participate in COP30 in Brazil, with training in climate negotiations, science, and justice.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1741295543/opportunities/covers/dekbtzibmavddlroosst.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 5,
    date_of_events: "2025-11-05 to 2025-11-21",
    eventMode: "volunteer",
    locationName: "Belém, Brazil",
    teacher_id: null,
    associationId: "assoc_40",
    additional: "allowAll",
  },
  {
    _id: "event_41",
    title: "Elles Tech Tour 2025",
    desc: "La French Tech Maroc’s Elles Tech Tour promotes women in tech across five Moroccan cities, offering coaching and a tour of French Tech communities.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1741281989/opportunities/covers/erc5ahcbtgyfdtjsois1.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 45,
    date_of_events: "2025-04-01 to 2025-04-30",
    eventMode: "volunteer",
    locationName: "Casablanca, Morocco",
    teacher_id: null,
    associationId: "assoc_41",
    additional: "allowAll",
  },
  {
    _id: "event_42",
    title: "2nd Eco-Campus International Conference 2025",
    desc: "A conference in Kuala Lumpur discussing the role of higher education in sustainable development, fostering multi-disciplinary collaborations for eco-friendly practices.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1741139938/opportunities/covers/dvdzvbm7nhzprgdifyhk.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 5,
    date_of_events: "2025-09-18 to 2025-09-20",
    eventMode: "volunteer",
    locationName: "Kuala Lumpur, Malaysia",
    teacher_id: null,
    associationId: "assoc_42",
    additional: "allowAll",
  },
  {
    _id: "event_43",
    title: "Scholarships for International Students in Japan",
    desc: "Scholarships from the Japanese Government, JASSO, and private foundations support international students with tuition, living expenses, and travel for studies in Japan.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1741006370/opportunities/covers/ulck2qu6pzgakb8uf7k5.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 30,
    date_of_events: "2025-06-10 to 2025-06-15",
    eventMode: "volunteer",
    locationName: "Tokyo, Japan",
    teacher_id: null,
    associationId: "assoc_43",
    additional: "allowAll",
  },
  {
    _id: "event_44",
    title: "Ro'wad Al Shabab Al Arabi (Arab Youth Pioneers)",
    desc: "An initiative honoring 100 young Arab leaders under 35 for their contributions to leadership, innovation, and social impact, fostering a better future.",
    eventImage:
      "https://res.cloudinary.com/dghbzamnp/image/upload/v1740960206/opportunities/covers/t3ycfbg6han9yx2xkurt.jpg",
    userInfo: [{ profile_picture: "/images/default_user.jpg" }],
    sponsored: true,
    type_of_event: "volunteer",
    tickets: [],
    community_service_offered: 40,
    date_of_events: "2025-05-25 to 2025-05-30",
    eventMode: "volunteer",
    locationName: "Dubai, UAE",
    teacher_id: null,
    associationId: "assoc_44",
    additional: "allowAll",
  },
];

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    await connectDB();

    const preparedEvents = hardcodedEvents.map(prepareEvent);

    await Events.insertMany(preparedEvents);

    res
      .status(200)
      .json({ message: `${preparedEvents.length} events inserted.` });
  } catch (error) {
    console.error("Error inserting events:", error);
    res.status(500).json({ error: "Failed to insert events." });
  }
}
